datalore-env-format-version: "0.2"
datalore-package-manager: "pip"
datalore-base-env: "default"
dependencies:
- pip:
  - iplantuml==0.1.1
  - pyarrow==12.0.1
  - folium==0.14.0
  - openai==0.27.8
  - langchain==0.0.268
